services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - KAFKA_BROKERS
      - KAFKA_TOPIC
